import Link from "next/link"
import { ArrowLeft, FileText } from "lucide-react"

const SECTIONS = [
  {
    title: "Use Of Alibi",
    body: [
      "Alibi is a time-tracking, note-taking, calendar-sync, and reflection tool.",
      "You are responsible for the information you enter into Alibi and for how you use any reflections or summaries generated by the app.",
      "You must use the app lawfully and must not attempt to interfere with, reverse engineer, abuse, or disrupt the service.",
    ],
  },
  {
    title: "Accounts",
    body: [
      "You are responsible for maintaining access to your account and for activity under your account.",
      "You should use accurate account information and keep your authentication methods secure.",
      "We may restrict or terminate access if the app is abused, used unlawfully, or used in a way that risks harm to the service or other users.",
    ],
  },
  {
    title: "Your Content",
    body: [
      "You keep ownership of the notes, time blocks, chat messages, and other content you create in Alibi.",
      "You grant Alibi permission to process your content only as needed to provide the app, including storage, search, reflection, calendar sync, AI processing, voice transcription, and support/debugging.",
      "You are responsible for ensuring that you have the right to enter, upload, or sync any content you provide.",
    ],
  },
  {
    title: "AI And Reflections",
    body: [
      "Alibi may use AI systems to classify messages, generate reflections, summarize notes, extract insights, or help reconstruct time blocks.",
      "AI output can be incomplete or wrong. It is provided for reflection and organization, not as professional, medical, legal, financial, or therapeutic advice.",
      "You should review important information before relying on it.",
    ],
  },
  {
    title: "Integrations",
    body: [
      "If you connect Google Calendar, Alibi may create and manage a separate alibi calendar and events created by Alibi.",
      "If you save a custom AI provider key, Alibi may send relevant app context to the provider and model you select.",
      "If you use voice features, Alibi may send audio or text to a voice provider for transcription or speech generation.",
      "Third-party services may have their own terms, privacy policies, and availability limits.",
    ],
  },
  {
    title: "Service Availability",
    body: [
      "Alibi is provided as-is and may change, pause, or become unavailable.",
      "We do not guarantee uninterrupted service, preservation of all data, or compatibility with every third-party provider.",
      "You should keep your own copies of important information when needed.",
    ],
  },
  {
    title: "Limitations",
    body: [
      "To the extent permitted by law, Alibi is not liable for indirect, incidental, special, consequential, or punitive damages.",
      "Alibi is not responsible for decisions you make based on app output, AI-generated reflections, synced calendar events, or third-party provider responses.",
    ],
  },
  {
    title: "Changes",
    body: [
      "These terms may be updated as Alibi changes.",
      "Continued use of the app after updates means you accept the updated terms.",
    ],
  },
  {
    title: "Contact",
    body: [
      "For questions about these terms, contact the support email listed for Alibi in the product site, OAuth consent screen, or related app listing.",
    ],
  },
]

export default function TermsPage() {
  return (
    <main className="alibi-page min-h-screen px-6 py-8">
      <div className="mx-auto max-w-4xl">
        <Link
          href="/"
          className="inline-flex items-center gap-2 rounded-xl px-2 py-1.5 text-sm font-semibold text-alibi-teal transition hover:bg-alibi-lavender/10 hover:text-alibi-pink hover:shadow-[inset_0_2px_5px_rgba(50,83,199,0.08)]"
        >
          <ArrowLeft className="h-4 w-4" />
          alibi
        </Link>

        <section className="alibi-card-pop mt-5 p-6 sm:p-8">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="font-mono text-xs font-black uppercase tracking-[0.12em] text-alibi-teal">
                terms
              </p>
              <h1 className="mt-2 text-3xl font-black tracking-tight text-alibi-blue sm:text-4xl">
                Terms of Service
              </h1>
              <p className="mt-2 text-sm font-semibold text-alibi-teal">
                Last updated: May 20, 2026
              </p>
            </div>
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-alibi-pink/15 text-alibi-pink">
              <FileText className="h-5 w-5" />
            </div>
          </div>

          <p className="mt-6 text-base font-semibold leading-7 text-alibi-ink">
            These terms describe the rules for using Alibi. They are a practical product template
            and should be reviewed before production launch.
          </p>
        </section>

        <div className="mt-5 space-y-4">
          {SECTIONS.map((section) => (
            <section key={section.title} className="alibi-card p-5">
              <h2 className="text-xl font-black text-alibi-blue">{section.title}</h2>
              <ul className="mt-3 space-y-2">
                {section.body.map((item) => (
                  <li key={item} className="text-sm font-semibold leading-6 text-alibi-teal">
                    {item}
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>
      </div>
    </main>
  )
}
